server:
  port: 8989
  servlet:
    context-path: /pzh

spring:
  application:
    name: conference_information_management

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pzh_meeting_management?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: zp.6330330

mybatis:
  type-aliases-package: com.pzh.zp.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
